version: '3.8'

name: gamer-metrics

services:
  pg.db:
    image: postgres:14.7-alpine
    container_name: pg-db
    environment:
      POSTGRES_USER: gameruser
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "books_db" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "15432:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - gamer_metrics_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  pg.admin:
    image: dpage/pgadmin4:7
    container_name: pg-admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - gamer_metrics_pg_data:/var/lib/pgadmin

volumes:
  gamer_metrics_db_data:
  gamer_metrics_pg_data: